#ifndef LNURLVAULT_NOTE_ART_H
#define LNURLVAULT_NOTE_ART_H

#include <stdbool.h>
#include <stdint.h>

/* The boot note's engraved parts, generated by tools/engrave.py into
 * note_art.c. This header is hand-written and is the contract between them.
 *
 * Each sprite is a 4-bit coverage mask -- how much of its colour lands on
 * each pixel, 0 (none) to 15 (all) -- packed two pixels to a byte with the
 * left pixel in the high nibble and every row starting on a byte boundary.
 * Coverage rather than colour because the note is an engraving: one ink per
 * pass, and what varies is how much of it. That is also what makes the masks
 * small (a few kilobytes for both panels) and the compositing one multiply.
 *
 * No ESP-IDF here. note_scene.c reads these on the device and in
 * test/native, so what the preview shows is what the glass gets. */

/* The printing passes, in order. A real note is printed the same way: the
 * underprint, then the intaglio, then the letterpress numbering. Each one is
 * a boot step, and a step that fails leaves its pass off the note. */
typedef enum {
    NOTE_LAYER_UNDERPRINT = 1, /* STORAGE: border, crest, rosette */
    NOTE_LAYER_INTAGLIO = 2,   /* IDENTITY: the name and the promise */
    NOTE_LAYER_NUMBERING = 3,  /* LINK: the serial */
} note_layer_t;

/* Which of the note's inks a mask is printed in. Resolved to an RGB565
 * value by the compositor, so the table carries no colour of its own and
 * cannot disagree with palette.h. */
typedef enum {
    NOTE_ROLE_ACCENT, /* what the plates are engraved in: PALETTE_PLATE, a grey */
    NOTE_ROLE_INK,    /* the card's text colour */
    NOTE_ROLE_DIM,    /* the card's second weight */
} note_role_t;

typedef struct {
    note_layer_t layer;
    note_role_t role;
    bool two_sided;      /* on the back of the note as well: the border is,
                            the crest and the type are not */
    int x, y, w, h;      /* panel pixels, top-left and size */
    const uint8_t *mask; /* (w + 1) / 2 bytes per row, h rows */
} note_sprite_t;

typedef struct {
    int w, h;       /* the panel this was engraved for */
    int band, bar;  /* the band and bar heights the tool assumed -- see
                       note_scene_begin() on what happens if they differ */
    int note_x, note_y, note_w, note_h;     /* the paper */
    int inner_x, inner_y, inner_w, inner_h; /* inside the border: where the
                                               serial and the self-check go */
    int rosette_cx, rosette_cy, rosette_r;  /* where the identity is engraved */
    int serial_scale, serial_x, serial_y;   /* where the numbering is stamped, and
                                               how big: the readable floor */
    const note_sprite_t *sprites;
    int nsprites;
} note_art_t;

/* The table for a panel of exactly this size, or NULL. A panel nobody has
 * engraved a note for still boots and still gets a note -- paper, rosette,
 * serial, self-check -- just without the parts that needed a typeface. */
const note_art_t *note_art_for(int w, int h);

#endif
